---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: hello-world
          image: jayamorin/hello-world:v1.0.3
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
          startupProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
