name: "Build docker image"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jayamorin
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Get current timedate
        run: echo "NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Pull latest image and build
        env:
          DATETIME_NOW: ${{ env.NOW }}
          COMMIT_HASH: ${{ github.sha }}
          BUILD_TAG: ${{ github.ref_name }}
        run: |
          cd src/hello-world
          docker pull jayamorin/hello-world:latest
          docker build -t jayamorin/hello-world:latest \
            --build-arg COMMIT_HASH=$COMMIT_HASH \
            --build-arg BUILD_DATE=${DATETIME_NOW} \
            --build-arg BUILD_TAG=${BUILD_TAG} .

      - name: Push to hub.docker.com
        env:
          BUILD_TAG: ${{ github.ref_name }}
        run: |
          docker tag jayamorin/hello-world:latest jayamorin/hello-world:$BUILD_TAG
          docker push jayamorin/hello-world:latest
          docker push jayamorin/hello-world:$BUILD_TAG
          docker inspect jayamorin/hello-world:$BUILD_TAG
