name: "Test docker image"

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "master"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jayamorin
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Get current timedate
        id: date
        run: echo "{date}={$(date -u +'%Y-%m-%dT%H:%M:%SZ')}" >> $GITHUB_STATE

      - name: Pull latest image and build
        env:
          DATETIME_NOW: ${{ env.date }}
          COMMIT_HASH: ${{ github.sha }}
          BUILD_TAG: ${{ github.ref_name }}
        run: |
          cd src/hello-world
          docker pull jayamorin/hello-world:latest
          docker build -t jayamorin/hello-world:latest \
            --build-arg COMMIT_HASH=$COMMIT_HASH \
            --build-arg BUILD_DATE=${DATETIME_NOW} \
            --build-arg BUILD_TAG=${BUILD_TAG} .
          docker inspect jayamorin/hello-world:latest
